paths:
  mimic3_clinical_root: /u/project/jchiang/njchiang/data/physionet/mimic-iii-clinical-database-1.4
  mimic4_clinical_root: /u/project/jchiang/njchiang/data/physionet/mimic-iv-2.2/mimic-iv-2.2
  mimic3_waveforms_root: /path/to/waveforms
  mimic4_waveforms_root:
  derived: /u/project/jchiang/tsisson/mimic/data/derived
  gem: /u/project/jchiang/tsisson/mimic/data/gem

signals: ['PLETH', 'II', 'ABP']